# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.1.0/rest-clients.json
RestClients:
  #URI: https://<storage-account>.blob.core.windows.net
  Azure Blob Storage Demo:
    UUID: 2ffe8054-31c7-4815-94fa-1617a40ed34c
    Url: https://storage-account.blob.core.windows.net
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
