# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/rest-clients-2.json
RestClients:
  #URI: https://<storage-account>.blob.core.windows.net
  AzureBlobStorage:
    Name: AzureBlobStorage
    Url: ${ivy.var.AzureBlob.BaseUrl}
    Features:
      - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    LegacyUUID: a61f273e-f451-4fe3-a2b7-9f62fddb7bf3
